### ISSUE TITLE
Unable to pass 11 params

### ISSUE THREAD

**Issue by SwinX** [nathan7/new-operator#1]
On my project I currently use constructors with 11 params. May you please extend the lib so I will be able to pass 11 params?

**Comment by edef1c** [comment]
This _should_ work, the 1-10 param thing is mainly for native constructors (and occasionally a nice micro-optimisation)
Are there native constructors with 11 parameters?

**Comment by edef1c** [comment]
Ah! I just realised ES6 classes behave the same as native constructors, that explains it.

**Comment by edef1c** [comment]
Published as 1.0.4, enjoy :heart:
